In [62]:
!pip install requests
!pip install beautifulsoup4
!pip install lxml

Requirement already satisfied: requests in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests) (2022.12.7)
Requirement already satisfied: beautifulsoup4 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.12.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4) (2.4)
Requirement already satisfied: lxml in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (5.1.0)

In [63]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd

In [64]:
pokemon_name = []
all_pokemon = 'https://serebii.net/pokedex-sv/'
result = requests.get(all_pokemon)
soup = bs(result.content, 'lxml')

tables=soup.find_all('table')
second_table = tables[1]

options = second_table.find_all('option')
pokemon_names = [option.get_text(strip=True) for option in options]

pokemon_list = []
for option in options:
    text = option.get_text(strip=True)
    number, name = text.split(' ', 1) 
    pokemon_list.append((number, name))

for number, name in pokemon_list:
    print(name.lstrip())

001 - 151
Bulbasaur
Ivysaur
Venusaur
Charmander
Charmeleon
Charizard
Squirtle
Wartortle
Blastoise
Ekans
Arbok
Pikachu
Raichu
Sandshrew
Sandslash
Clefairy
Clefable
Vulpix
Ninetales
Jigglypuff
Wigglytuff
Oddish
Gloom
Vileplume
Venonat
Venomoth
Diglett
Dugtrio
Meowth
Persian
Psyduck
Golduck
Mankey
Primeape
Growlithe
Arcanine
Poliwag
Poliwhirl
Poliwrath
Bellsprout
Weepinbell
Victreebel
Tentacool
Tentacruel
Geodude
Graveler
Golem
Slowpoke
Slowbro
Magnemite
Magneton
Doduo
Dodrio
Seel
Dewgong
Grimer
Muk
Shellder
Cloyster
Gastly
Haunter
Gengar
Drowzee
Hypno
Voltorb
Electrode
Exeggcute
Exeggutor
Hitmonlee
Hitmonchan
Koffing
Weezing
Rhyhorn
Rhydon
Chansey
Horsea
Seadra
Scyther
Electabuzz
Magmar
Tauros
Magikarp
Gyarados
Lapras
Ditto
Eevee
Vaporeon
Jolteon
Flareon
Porygon
Snorlax
Articuno
Zapdos
Moltres
Dratini
Dragonair
Dragonite
Mewtwo
Mew
152 - 251
Chikorita
Bayleef
Meganium
Cyndaquil
Quilava
Typhlosion
Totodile
Croconaw
Feraligatr
Sentret
Furret
Hoothoot
Noctowl
Spinarak
Ariados
Chinchou
Lanturn
Pichu
Cleffa
Igglybuff
Mareep
Flaaffy
Ampharos
Bellossom
Marill
Azumarill
Sudowoodo
Politoed
Hoppip
Skiploom
Jumpluff
Aipom
Sunkern
Sunflora
Yanma
Wooper
Quagsire
Espeon
Umbreon
Murkrow
Slowking
Misdreavus
Girafarig
Pineco
Forretress
Dunsparce
Gligar
Snubbull
Granbull
Qwilfish
Scizor
Heracross
Sneasel
Teddiursa
Ursaring
Slugma
Magcargo
Swinub
Piloswine
Delibird
Skarmory
Houndour
Houndoom
Kingdra
Phanpy
Donphan
Porygon2
Stantler
Smeargle
Tyrogue
Hitmontop
Elekid
Magby
Blissey
Raikou
Entei
Suicune
Larvitar
Pupitar
Tyranitar
Lugia
Ho-Oh
252-386
Treecko
Grovyle
Sceptile
Torchic
Combusken
Blaziken
Mudkip
Marshtomp
Swampert
Poochyena
Mightyena
Lotad
Lombre
Ludicolo
Seedot
Nuzleaf
Shiftry
Wingull
Pelipper
Ralts
Kirlia
Gardevoir
Surskit
Masquerain
Shroomish
Breloom
Slakoth
Vigoroth
Slaking
Makuhita
Hariyama
Azurill
Nosepass
Sableye
Meditite
Medicham
Plusle
Minun
Volbeat
Illumise
Gulpin
Swalot
Numel
Camerupt
Torkoal
Spoink
Grumpig
Trapinch
Vibrava
Flygon
Cacnea
Cacturne
Swablu
Altaria
Zangoose
Seviper
Barboach
Whiscash
Corphish
Crawdaunt
Feebas
Milotic
Shuppet
Banette
Duskull
Dusclops
Tropius
Chimecho
Snorunt
Glalie
Luvdisc
Bagon
Shelgon
Salamence
Beldum
Metang
Metagross
Regirock
Regice
Registeel
Latias
Latios
Kyogre
Groudon
Rayquaza
Jirachi
Deoxys
387-493
Turtwig
Grotle
Torterra
Chimchar
Monferno
Infernape
Piplup
Prinplup
Empoleon
Starly
Staravia
Staraptor
Kricketot
Kricketune
Shinx
Luxio
Luxray
Cranidos
Rampardos
Shieldon
Bastiodon
Combee
Vespiquen
Pachirisu
Buizel
Floatzel
Shellos
Gastrodon
Ambipom
Drifloon
Drifblim
Mismagius
Honchkrow
Chingling
Stunky
Skuntank
Bronzor
Bronzong
Bonsly
Happiny
Spiritomb
Gible
Gabite
Garchomp
Munchlax
Riolu
Lucario
Hippopotas
Hippowdon
Croagunk
Toxicroak
Finneon
Lumineon
Snover
Abomasnow
Weavile
Magnezone
Rhyperior
Electivire
Magmortar
Yanmega
Leafeon
Glaceon
Gliscor
Mamoswine
Porygon-Z
Gallade
Probopass
Dusknoir
Froslass
Rotom
Uxie
Mesprit
Azelf
Dialga
Palkia
Heatran
Regigigas
Giratina
Cresselia
Phione
Manaphy
Darkrai
Shaymin
Arceus
494-649
Snivy
Servine
Serperior
Tepig
Pignite
Emboar
Oshawott
Dewott
Samurott
Blitzle
Zebstrika
Drilbur
Excadrill
Timburr
Gurdurr
Conkeldurr
Sewaddle
Swadloon
Leavanny
Cottonee
Whimsicott
Petilil
Lilligant
Basculin
Sandile
Krokorok
Krookodile
Scraggy
Scrafty
Zorua
Zoroark
Minccino
Cinccino
Gothita
Gothorita
Gothitelle
Solosis
Duosion
Reuniclus
Ducklett
Swanna
Deerling
Sawsbuck
Foongus
Amoonguss
Alomomola
Joltik
Galvantula
Tynamo
Eelektrik
Eelektross
Litwick
Lampent
Chandelure
Axew
Fraxure
Haxorus
Cubchoo
Beartic
Cryogonal
Mienfoo
Mienshao
Golett
Golurk
Pawniard
Bisharp
Rufflet
Braviary
Vullaby
Mandibuzz
Deino
Zweilous
Hydreigon
Larvesta
Volcarona
Cobalion
Terrakion
Virizion
Tornadus
Thundurus
Reshiram
Zekrom
Landorus
Kyurem
Keldeo
Meloetta
650-721
Chespin
Quilladin
Chesnaught
Fennekin
Braixen
Delphox
Froakie
Frogadier
Greninja
Fletchling
Fletchinder
Talonflame
Scatterbug
Spewpa
Vivillon
Litleo
Pyroar
Flabébé
Floette
Florges
Skiddo
Gogoat
Espurr
Meowstic
Inkay
Malamar
Skrelp
Dragalge
Clauncher
Clawitzer
Sylveon
Hawlucha
Dedenne
Carbink
Goomy
Sliggoo
Goodra
Klefki
Phantump
Trevenant
Bergmite
Avalugg
Noibat
Noivern
Diancie
Hoopa
Volcanion
722-809
Rowlet
Dartrix
Decidueye
Litten
Torracat
Incineroar
Popplio
Brionne
Primarina
Pikipek
Trumbeak
Toucannon
Yungoos
Gumshoos
Grubbin
Charjabug
Vikavolt
Crabrawler
Crabominable
Oricorio
Cutiefly
Ribombee
Rockruff
Lycanroc
Mareanie
Toxapex
Mudbray
Mudsdale
Dewpider
Araquanid
Fomantis
Lurantis
Salandit
Salazzle
Bounsweet
Steenee
Tsareena
Comfey
Oranguru
Passimian
Sandygast
Palossand
Minior
Komala
Mimikyu
Bruxish
Jangmo-o
Hakamo-o
Kommo-o
Cosmog
Cosmoem
Solgaleo
Lunala
Necrozma
Magearna
810-905
Grookey
Thwackey
Rillaboom
Scorbunny
Raboot
Cinderace
Sobble
Drizzile
Inteleon
Skwovet
Greedent
Rookidee
Corvisquire
Corviknight
Chewtle
Drednaw
Rolycoly
Carkol
Coalossal
Applin
Flapple
Appletun
Silicobra
Sandaconda
Cramorant
Arrokuda
Barraskewda
Toxel
Toxtricity
Sinistea
Polteageist
Hatenna
Hattrem
Hatterene
Impidimp
Morgrem
Grimmsnarl
Perrserker
Milcery
Alcremie
Falinks
Pincurchin
Snom
Frosmoth
Stonjourner
Eiscue
Indeedee
Morpeko
Cufant
Copperajah
Duraludon
Dreepy
Drakloak
Dragapult
Zacian
Zamazenta
Eternatus
Kubfu
Urshifu
Zarude
Regieleki
Regidrago
Glastrier
Spectrier
Calyrex
Wyrdeer
Kleavor
Ursaluna
Basculegion
Sneasler
Overqwil
Enamorus
906-1025
Sprigatito
Floragato
Meowscarada
Fuecoco
Crocalor
Skeledirge
Quaxly
Quaxwell
Quaquaval
Lechonk
Oinkologne
Tarountula
Spidops
Nymble
Lokix
Pawmi
Pawmo
Pawmot
Tandemaus
Maushold
Fidough
Dachsbun
Smoliv
Dolliv
Arboliva
Squawkabilly
Nacli
Naclstack
Garganacl
Charcadet
Armarouge
Ceruledge
Tadbulb
Bellibolt
Wattrel
Kilowattrel
Maschiff
Mabosstiff
Shroodle
Grafaiai
Bramblin
Brambleghast
Toedscool
Toedscruel
Klawf
Capsakid
Scovillain
Rellor
Rabsca
Flittle
Espathra
Tinkatink
Tinkatuff
Tinkaton
Wiglett
Wugtrio
Bombirdier
Finizen
Palafin
Varoom
Revavroom
Cyclizar
Orthworm
Glimmet
Glimmora
Greavard
Houndstone
Flamigo
Cetoddle
Cetitan
Veluza
Dondozo
Tatsugiri
Annihilape
Clodsire
Farigiraf
Dudunsparce
Kingambit
Great Tusk
Scream Tail
Brute Bonnet
Flutter Mane
Slither Wing
Sandy Shocks
Iron Treads
Iron Bundle
Iron Hands
Iron Jugulis
Iron Moth
Iron Thorns
Frigibax
Arctibax
Baxcalibur
Gimmighoul
Gholdengo
Wo-Chien
Chien-Pao
Ting-Lu
Chi-Yu
Roaring Moon
Iron Valiant
Koraidon
Miraidon
Walking Wake
Iron Leaves
Dipplin
Poltchageist
Sinistcha
Okidogi
Munkidori
Fezandipiti
Ogerpon
Archaludon
Hydrapple
Gouging Fire
Raging Bolt
Iron Boulder
Iron Crown
Terapagos
Pecharunt

# Analisando a página do bubasaur

In [65]:
pokemon_website = 'https://serebii.net/pokedex-sv/bulbasaur/'
result = requests.get(pokemon_website)
content = result.text
soup = bs(content, 'lxml')

In [66]:
content = soup.find_all('table', class_='dextable')
content = content[1].find_all('td', class_='fooinfo')
content

[<td class="fooinfo">Bulbasaur</td>,
 <td class="fooinfo"><table cellpadding="0" cellspacing="0" width="120">
 <tr> <td><b>Japan</b>: </td><td>Fushigidane<br/>フシギダネ</td></tr>
 <tr> <td><b>French</b>: </td><td>Bulbizarre</td></tr>
 <tr> <td><b>German</b>: </td><td>Bisasam</td></tr>
 <tr> <td><b>Korean</b>: </td><td>이상해씨</td></tr>
 </table></td>,
 <td class="fooinfo"><table cellpadding="0" cellspacing="0" width="120"><tr> <td><b>National</b>: </td><td>#001</td></tr>
 <tr><td><b>Paldea</b>: </td><td>#---</td></tr>
 <tr><td><b>Kitakami</b>: </td><td>#---</td></tr>
 <tr><td><b>Blueberry</b>: </td><td>#164</td></tr>
 </table></td>,
 <td class="fooinfo"><table cellpadding="0" cellspacing="0" width="120"><tr> <td>Male <font color="#499FFF">♂</font>:</td><td>88%</td></tr><tr><td>Female <font color="#F6814A">♀</font>:</td><td>12%</td></tr></table></td>,
 <td class="fooinfo">Seed Pokémon</td>,
 <td class="fooinfo">2'04"<br/>
 			0.7m</td>,
 <td class="fooinfo">15.2lbs<br/>
 			6.9kg</td>,
 <td class="fooinfo">45</td>,
 <td class="fooinfo">2,560 Steps<br/>20 Cycles</td>]

In [67]:
df = pd.DataFrame()

In [68]:
name = content[0].get_text()
df['name'] = [name]
df

        name
0  Bulbasaur

In [69]:
gender = content[3].get_text()
male = gender.split(':')[1].split('%')[0]
female = gender.split(':')[2].split('%')[0]
df["percent_male"] = [male]
df["percent_female"] = [female]
df

        name percent_male percent_female
0  Bulbasaur           88             12

In [70]:
content_type = soup.find_all('table', class_='dextable')
content_type = content_type[1].find_all('td', class_='cen')
img_tag = content_type[0]
img_tag = img_tag.find_all('img')

pokemon_type = []

for i in img_tag:
    pokemon_type.append(i['alt'].split('-')[0])  

if len(pokemon_type) == 1:
    pokemon_type.append("null")

df["type_1"] = pokemon_type[0] 
df["type_2"] = pokemon_type[1]

df

        name percent_male percent_female type_1  type_2
0  Bulbasaur           88             12  Grass  Poison

In [71]:
classification = content[4].get_text()
df["classification"] = classification
df

        name percent_male percent_female type_1  type_2 classification
0  Bulbasaur           88             12  Grass  Poison   Seed Pokémon

In [72]:
height = content[5].get_text()
height = height.split('\t')[-1]
df["height"] = height
df

        name percent_male percent_female type_1  type_2 classification height
0  Bulbasaur           88             12  Grass  Poison   Seed Pokémon   0.7m

In [73]:
weight = content[6].get_text().split("\t")[-1]
df["weight"] = weight
df

,name,percent_male,percent_female,type_1,type_2,classification,height,weight
0,Bulbasaur,88,12,Grass,Poison,Seed Pokémon,0.7m,6.9kg

In [74]:
capture_rate = content[7].get_text()
df["capture_rate"] = capture_rate
df

,name,percent_male,percent_female,type_1,type_2,classification,height,weight,capture_rate
0,Bulbasaur,88,12,Grass,Poison,Seed Pokémon,0.7m,6.9kg,45

In [75]:
content[8]

In [80]:
content_abilities = content[4].find_all('td', class_='fooinfo')
content_abilities

[]